# Generated by Django 3.2.9 on 2022-05-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='available',
        ),
    ]
