# Generated by Django 3.2.9 on 2022-06-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_sponsored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sponsored',
        ),
        migrations.DeleteModel(
            name='SponsoredJobPost',
        ),
    ]
